name: 'HuskClaims'
description: '${description}'
author: 'William278'
website: 'https://william278.net/project/huskclaims'
main: 'net.william278.huskclaims.BukkitHuskClaims'
version: '${version}'
api-version: 1.17
libraries:
  - 'redis.clients:jedis:${jedis_version}'
  - 'com.mysql:mysql-connector-j:${mysql_driver_version}'
  - 'org.mariadb.jdbc:mariadb-java-client:${mariadb_driver_version}'
  - 'org.xerial:sqlite-jdbc:${sqlite_driver_version}'
softdepend:
  - 'LuckPerms'
  - 'HuskHomes'